var MSG = {
  title: "Código",
  blocks: "Bloques",
  linkTooltip: "Guarda y enlaza a los bloques.",
  runTooltip: "Ejecuta el programa en del escritorio.",
  badCode: "Error en el programa:\n%1",
  timeout: "Máximo de iteraciones alcanzado.",
  trashTooltip: "Borrar todos los bloques.",
  catLogic: "Lógica",
  catLoops: "Bucles",
  catMath: "Mates",
  catText: "Texto",
  catLists: "Listas",
  catColour: "Colores",
  catVariables: "Variables",
  catFunctions: "Funciones",
  listVariable: "lista",
  textVariable: "texto",
  httpRequestError: "Ocurrió un problema con la petición.",
  linkAlert: "Comparte tus bloques con este enlace:\n\n%1",
  hashError: "Lo siento, '%1' no se corresponde con ningún programa guardado.",
  xmlError: "No he podido cargar tu fichero guardado. Quizás ha sido creado con otra versión de Blockly?",
  badXml: "Error procesando el XML:\n%1\n\nSelecciona 'OK' para descartar tus cambios o 'Cancelar' para seguir editando el XML."
};
